### PR TITLE
FAQs page done

### PR DESCRIPTION
**Pull request by dikshantgupta2589**
Responsivity completed for all devices Contribution by :- Vishist Nilav Bhagabati, Vedant Gadodia, Dikshant Gupta
Please Review @VDliveson
Solves #13

### CODE REVIEW

**Comment by VDliveson** [comment]
Pls review @RGTechPro @aarushi353

**Comment by VDliveson** [comment]
Seems fine

**Review by aarushi353 — APPROVED** [review]
Seem's alright to me @VDliveson

**Review by RGTechPro — APPROVED** [review]
Seems fine to me as well

**Pull request merged**
