### PR TITLE
Judges#1

### PR DESCRIPTION
**Pull request by achintya406**
Designed to be responsive for all devices.
Other Contributors:- @Aryan-401 @Avirat201189221 @Ikshan-Tango @sanchirang @aditya-talwar21 @Ave-Eren
Solves #18
Please Review @aarushi353

### CODE REVIEW

**Review by RGTechPro — APPROVED** [review]
looks perfect!

**Review by VDliveson — COMMENTED** [review]
Seems unresponsive heading at 393-433

**Comment by VDliveson** [comment]
Seems fine to me

**Review by thetarandhiman — APPROVED** [review]
This is looking fine ! Will merge it!

**Comment by thetarandhiman** [comment]
Thanks for your contribution! Happy coding! :-)

**Pull request merged**
