### PR TITLE
Speakers#2

### LINKED ISSUE #9: Speakers

### PR DESCRIPTION
**Pull request by Ave-Eren**
+ Made responsive for all devices.
+ Other Contributors :- @Aryan-401 @Avirat201189221 @Ikshan-Tango 
+ Please Review @aarushi353 
+ Solves #9

### CODE REVIEW

**Comment by VDliveson** [comment]
Seems fine to me

**Review by RGTechPro — DISMISSED** [review]

**Comment by aarushi353** [comment]
Kindly work on the information display about the speaker @Ave-Eren @Aryan-401 @Avirat201189221 @Ikshan-Tango

**Comment by VDliveson** [comment]
Seems fine to me

**Review by VDliveson — COMMENTED** [review]
Ok seems fine

**Pull request merged**
