### PR TITLE
Contactus Page

### PR DESCRIPTION
**Pull request by Vansh-Batra10**
Responsivity completed for all devices
Contribution by :- Vansh Batra ,  Aarav Sahni ,  Ishan Agarwal , Bhavya Bhalla
Please Review @RGTechPro 
Solves #23

### CODE REVIEW

**Comment by aarushi353** [comment]
Screenshot 2022-01-17 153052

**Comment by aarushi353** [comment]
Just a few changes, the font used for Contact us doesn't match with the remaining pages, so kindly change that. Secondly, decrease the margin-top for screen sizes less than 420px for the box containing 2 links.

**Comment by BhavyaBhalla27** [comment]
Ok maam will do that.

**Comment by VDliveson** [comment]
Pls change the page as asked

**Review by RGTechPro — APPROVED** [review]
Seems fine to me

**Review by aarushi353 — APPROVED** [review]
Seem's alright now!
@RGTechPro

**Pull request merged**
